// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/conversations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of conversations for the authenticated user, ordered by most recent activity. Returns JSON:API compliant response with meta and links for pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "List conversations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max results (default 20)",
                        "name": "page[limit]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "page[offset]",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of conversations",
                        "schema": {
                            "$ref": "#/definitions/handler.ConversationListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Starts a new conversation between the authenticated user and the target user. If a conversation already exists it is returned. Both users must mutually follow each other. Returns JSON:API compliant response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Create or get a conversation",
                "parameters": [
                    {
                        "description": "Target user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.createConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversation already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.ConversationResponse"
                        }
                    },
                    "201": {
                        "description": "Conversation created",
                        "schema": {
                            "$ref": "#/definitions/handler.ConversationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "403": {
                        "description": "Users do not mutually follow each other",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a conversation by ID. The authenticated user must be a participant. Returns JSON:API compliant response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conversations"
                ],
                "summary": "Get a conversation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversation",
                        "schema": {
                            "$ref": "#/definitions/handler.ConversationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — not a participant",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    }
                }
            }
        },
        "/conversations/{id}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated message history for a conversation, ordered newest first. The authenticated user must be a participant. Returns JSON:API compliant response with meta and links for pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 50)",
                        "name": "page[limit]",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "page[offset]",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of messages",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — not a participant",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "404": {
                        "description": "Conversation not found",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a text message or POI share to the conversation. The authenticated user must be a participant. Returns JSON:API compliant response.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message created",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden — not a participant",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "404": {
                        "description": "Conversation not found",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONAPIErrorsResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the service status in JSON:API format",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service status",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthJSONAPIResponse"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "Upgrades to WebSocket. The first client frame must be an auth message: {\"type\":\"auth\",\"token\":\"\u003cjwt\u003e\"}",
                "tags": [
                    "websocket"
                ],
                "summary": "Open a WebSocket connection",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ConversationAttributes": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T10:30:00Z"
                },
                "last_message_at": {
                    "type": "string",
                    "example": "2025-01-15T14:20:00Z"
                },
                "user1_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "user2_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                }
            }
        },
        "handler.ConversationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "attributes": {
                                "$ref": "#/definitions/handler.ConversationAttributes"
                            },
                            "id": {
                                "type": "string",
                                "example": "550e8400-e29b-41d4-a716-446655440000"
                            },
                            "links": {
                                "$ref": "#/definitions/handler.JSONAPILinks"
                            },
                            "type": {
                                "type": "string",
                                "example": "conversations"
                            }
                        }
                    }
                },
                "links": {
                    "type": "object",
                    "properties": {
                        "first": {
                            "type": "string",
                            "example": "/api/v1/conversations?page[limit]=20\u0026page[offset]=0"
                        },
                        "next": {
                            "type": "string",
                            "example": "/api/v1/conversations?page[limit]=20\u0026page[offset]=20"
                        },
                        "prev": {
                            "type": "string",
                            "example": "/api/v1/conversations?page[limit]=20\u0026page[offset]=0"
                        },
                        "self": {
                            "type": "string",
                            "example": "/api/v1/conversations?page[limit]=20\u0026page[offset]=0"
                        }
                    }
                },
                "meta": {
                    "$ref": "#/definitions/handler.JSONAPIMeta"
                }
            }
        },
        "handler.ConversationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "attributes": {
                            "$ref": "#/definitions/handler.ConversationAttributes"
                        },
                        "id": {
                            "type": "string",
                            "example": "550e8400-e29b-41d4-a716-446655440000"
                        },
                        "links": {
                            "$ref": "#/definitions/handler.JSONAPILinks"
                        },
                        "type": {
                            "type": "string",
                            "example": "conversations"
                        }
                    }
                }
            }
        },
        "handler.HealthJSONAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "attributes": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                }
                            }
                        },
                        "id": {
                            "type": "string",
                            "example": "550e8400-e29b-41d4-a716-446655440000"
                        },
                        "type": {
                            "type": "string",
                            "example": "conversations"
                        }
                    }
                }
            }
        },
        "handler.JSONAPIError": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "conversation not found"
                },
                "status": {
                    "type": "string",
                    "example": "404"
                },
                "title": {
                    "type": "string",
                    "example": "Not Found"
                }
            }
        },
        "handler.JSONAPIErrorsResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.JSONAPIError"
                    }
                }
            }
        },
        "handler.JSONAPILinks": {
            "type": "object",
            "properties": {
                "self": {
                    "type": "string",
                    "example": "/api/v1/conversations/550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "handler.JSONAPIMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "handler.MessageAttributes": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Hello! How are you?"
                },
                "conversation_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-01-15T14:20:00Z"
                },
                "poi_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "sender_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "share_intent": {
                    "type": "string",
                    "example": "visit"
                },
                "status": {
                    "type": "string",
                    "example": "sent"
                },
                "type": {
                    "type": "string",
                    "example": "text"
                }
            }
        },
        "handler.MessageListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "attributes": {
                                "$ref": "#/definitions/handler.MessageAttributes"
                            },
                            "id": {
                                "type": "string",
                                "example": "550e8400-e29b-41d4-a716-446655440000"
                            },
                            "links": {
                                "$ref": "#/definitions/handler.JSONAPILinks"
                            },
                            "type": {
                                "type": "string",
                                "example": "conversations"
                            }
                        }
                    }
                },
                "links": {
                    "type": "object",
                    "properties": {
                        "first": {
                            "type": "string",
                            "example": "/api/v1/conversations/550e8400-e29b-41d4-a716-446655440000/messages?page[limit]=50\u0026page[offset]=0"
                        },
                        "next": {
                            "type": "string"
                        },
                        "prev": {
                            "type": "string"
                        },
                        "self": {
                            "type": "string",
                            "example": "/api/v1/conversations/550e8400-e29b-41d4-a716-446655440000/messages?page[limit]=50\u0026page[offset]=0"
                        }
                    }
                },
                "meta": {
                    "$ref": "#/definitions/handler.JSONAPIMeta"
                }
            }
        },
        "handler.MessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "attributes": {
                            "$ref": "#/definitions/handler.MessageAttributes"
                        },
                        "id": {
                            "type": "string",
                            "example": "550e8400-e29b-41d4-a716-446655440000"
                        },
                        "links": {
                            "$ref": "#/definitions/handler.JSONAPILinks"
                        },
                        "type": {
                            "type": "string",
                            "example": "conversations"
                        }
                    }
                }
            }
        },
        "handler.createConversationRequest": {
            "type": "object",
            "properties": {
                "target_user_id": {
                    "type": "string"
                }
            }
        },
        "handler.sendMessageRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "poi_id": {
                    "type": "string"
                },
                "share_intent": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the JWT token. Example: \"Bearer eyJhbGci...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Curiosity Chat API",
	Description:      "Real-time 1-on-1 chat microservice for the Curiosity platform. Users who mutually follow each other can exchange messages and share POIs via WebSockets.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
